// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi7.Datos;

#nullable disable

namespace WebApi7.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi7.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MetrosCuadrados")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<int>("Tarifa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Casa donde se vive Byron",
                            FechaActualizacion = new DateTime(2024, 7, 25, 2, 8, 26, 762, DateTimeKind.Local).AddTicks(30),
                            FechaCreacion = new DateTime(2024, 7, 25, 2, 8, 26, 762, DateTimeKind.Local).AddTicks(45),
                            ImagenUrl = "",
                            MetrosCuadrados = 400.0,
                            Nombre = "Casa Byron",
                            Ocupantes = 4,
                            Tarifa = 5
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "ABC",
                            Detalle = "Joselandia",
                            FechaActualizacion = new DateTime(2024, 7, 25, 2, 8, 26, 762, DateTimeKind.Local).AddTicks(49),
                            FechaCreacion = new DateTime(2024, 7, 25, 2, 8, 26, 762, DateTimeKind.Local).AddTicks(50),
                            ImagenUrl = "",
                            MetrosCuadrados = 800.0,
                            Nombre = "Casa Jose",
                            Ocupantes = 10,
                            Tarifa = 44
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
